version: '3.8'
services:
  timer-app:
    image: timer-app
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - pomodoro_database
  pomodoro_database:
    image: "postgres:14-alpine"
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pomodoro_database
